image: rust

test:
  script:
    - rustc --version
    - cargo --version
    - cargo test
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - cargo install cargo-audit
    - cargo audit
